{
 "title": "Loki1.0 Metrics",
 "description": "Loki metrics ",
 "tags": [
  "Loki ",
  "promtail"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Log Messages ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_log_messages_total{instance=\"loki:3100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunks Stored Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Boltdb shipper compactor run",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(loki_boltdb_shipper_compactor_running)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "description": "Current Alerts",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "loki_panic_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache bytes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(le) (rate(loki_cache_value_size_bytes_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{container_name=\"prometheus_container\"}"
    }
   ]
  },
  {
   "title": "Api Request Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{compose_project=\"aidedeapi\"} |= `` | logfmt --strict"
    }
   ]
  },
  {
   "title": "Promtail Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{container_name=\"promtail_container\"}"
    }
   ]
  },
  {
   "title": "Nginx Container",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "{container_name=\"nginx_container\"} |= ``"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Boltdb Shipper Requests",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(loki_boltdb_shipper_request_duration_seconds_count{instance=\"loki:3100\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}