{
 "title": "Nginx-Prometheus Exporter",
 "tags": [
  "nginx prometheus exporter ",
  "nginx",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Nginx Exporter Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter build info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "seconds summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=\"nginx-exporter:9113\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Runtime Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" },
    { "expr": "go_memstats_heap_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "metric handler request ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}