server:
  http_listen_port: 9080   
  grpc_listen_port: 0       

positions:
  filename: /var/log/positions.yaml  

clients:
  - url: http://loki:3100/loki/api/v1/push  

scrape_configs:
  - job_name: docker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log  

  - job_name: system_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system_logs
          __path__: /var/log/*.log  
